name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build and run tests
      env:
        AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      run: |
        echo "API_KEY=${{ secrets.AUTH0_DOMAIN }}" >> .env
        echo "DB_PASSWORD=${{ secrets.AUTH0_CLIENT_ID }}" >> .env
        npm run build
        npm test
